<?php

namespace frontend\modules\api\controllers;

use common\behance\traits\RepoTrait;
use common\classes\Debug;
use common\models\YoutubeQueue;
use frontend\components\Youtube;

class YoutubeController extends \yii\web\Controller
{
    use RepoTrait;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionNext()
    {
        $res = YoutubeQueue::getNextArray();
        if(!$res){
            return ['error' => 'No queue'];
        }
        $res['proxy'] = $this->getRandomProxy();

        return $res;
    }

    public function actionGetQueues($count)
    {
        $res = YoutubeQueue::getQueues($count);

        return $res;
    }

    public function actionDecrementQueue($id)
    {
        if (YoutubeQueue::decrementQueue($id)) {

            return ["status" => "Success"];
        }

        return ["status" => "Error"];
    }

    public function actionGetDuration($id)
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $youtube = new Youtube();

        return ['result' => $youtube->getDuration($id)];
    }
}
